name: run-test

on:
  pull_request:
    branches:
      - main

jobs:
  run-test:
    strategy:
      fail-fast: false

    runs-on: ubuntu-latest

    steps:
      - name: set up go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22

      - name: checkout gno
        uses: actions/checkout@v4
        with:
          repository: gnolang/gno
          ref: master
          path: ./gno

      - name: change block time to 2s
        run: |
          sed -i 's/ctx.Timestamp += (count \* 5)/ctx.Timestamp += (count \* 2)/g' ./gno/gnovm/tests/stdlibs/std/std.go

      - name: build gno
        run: |
          # which gno
          cd gno
          make install.gno
          which gno

      - name: set up python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: checkout gnoswap
        uses: actions/checkout@v4
        with:
          path: ./tmp/gnoswap

      - name: run setup.py to copy contracts
        run: |
          cd tmp/gnoswap
          python3 setup.py -w /home/runner/gnoswap/gnoswap

      - name: prepare `common` tests
        working-directory: /home/runner/gnoswap/gnoswap/gno/examples/gno.land/r/gnoswap/v1/common
        run: |
          for f in *_test.gno; do
            [ -e "$f" ] || continue

            if [ "$f" == "_helper_test.gno" ]; then
              continue
            fi

            mv "$f" "${f}A"
          done

      - name: run `common` tests one by one
        working-directory: /home/runner/gnoswap/gnoswap/gno/examples/gno.land/r/gnoswap/v1/common
        run: |
          TESTFILES=$(ls | grep '_test.gnoA$' || true)

          for f in $TESTFILES; do
            base="${f%.gnoA}"

            echo "---------------------------------------------------"
            echo "Renaming $f → $base.gno"
            mv "$f" "$base.gno"

            echo "Running 'gno test' for: $base.gno"
            gno test ./ -root-dir /home/runner/gnoswap/gnoswap/gno -v
            echo "Finished tests for: $base.gno"
            echo "---------------------------------------------------"

            echo "Reverting $base → $f"
            mv "$base" "$f"
          done
